### ISSUE TITLE
Cycle windows of the same class: attempt to index local 'source_c' (a nil value)

### ISSUE THREAD

**Issue by romabysen** [blueyed/awesome-cyclefocus#11]
I'm trying to cycle between clients of the same class using thise code:

``` lua
    cyclefocus.key({ modkey, }, "`", 1, {
            cycle_filter = cyclefocus.filters.same_class
    }),
```

but it results in the following error:
`W: awesome: event_handle_key:586: error running function: /home/lars/.config/awesome/cyclefocus/init.lua:133: attempt to index local 'source_c' (a nil value)`

It seems `source_c` is always `nil`.
Awesome is 3.5.6.

**Comment by blueyed** [comment]
Might be fixed by #14.

**Comment by petersohn** [comment]
I have awesome 4.1 and I am on the v4 version, and I have the same issue.

**Comment by blueyed** [comment]
@petersohn 
Can you post the whole backtrace, please?
I will fix it and release the v4 branch then,

**Comment by petersohn** [comment]
Unfortunately, I did not get a backtrace, only the one line that is about the same as above.

**Comment by blueyed** [comment]
I see now.
Do you use this filter in Awesome's `clientkeys`?

**Comment by blueyed** [comment]
I guess you will have the same issue with the `same_screen` filter, too?

**Comment by petersohn** [comment]
Yes, I have the issue with `same_screen`. Actually, that was the one I tried.

No, I don't use it in `clientkeys`. The only place where I use it are the global Alt+Tab key bindings, like this:

```lua
    awful.key({ "Mod1",         }, "Tab", function(_)
        cyclefocus.cycle(1, {
                modifier="Alt_L",
                cycle_filters={cyclefocus.filters.same_screen}
            })
    end),
    awful.key({ "Mod1", "Shift" }, "Tab", function(_)
        cyclefocus.cycle(-1, {
                modifier="Alt_L",
                cycle_filters={cyclefocus.filters.same_screen}
            })
```

**Comment by blueyed** [comment]
You have to use it in `clientkeys`.
Otherwise we cannot determine what to filter on.. the `source_c` is the client you are coming from, and is needed to get the screen/class etc from.

(We could add some checks / feedback when those filters are used incorrectly eventually.)

**Comment by petersohn** [comment]
I tried putting it in clientkeys, and I get the same error message there too.

**Comment by petersohn** [comment]
It works this way, though it is not documented, so I had to look it up in the code:

```lua
    awful.key({ "Mod1",         }, "Tab", function(c)
        cyclefocus.cycle(1, {
                modifier="Alt_L",
                cycle_filters={cyclefocus.filters.same_screen},
                initiating_client=c
            })
    end),
    awful.key({ "Mod1", "Shift" }, "Tab", function(_)
        cyclefocus.cycle(-1, {
                modifier="Alt_L",
                cycle_filters={cyclefocus.filters.same_screen},
                initiating_client=c
            })
    end)
```

However, I find it strange that this is needed, because pressing the ESC key returns to the original client even when I do not use `initiating_client`, so the widget should know about the initiating client even without that.

**Comment by blueyed** [comment]
Yeah, we could make use of the focused/initial client here.
I will check what's wrong here, maybe tomorrow.
Thanks for your investigation.

**Comment by blueyed** [comment]
@florian-wagner 
Can you post the whole error, please?
Which awesomeWM are you using?
How do you configure awesome-cyclefocus?  Do you use the filter in/via `clientkeys`?

**Comment by blueyed** [comment]
@petersohn 
Using `cyclefocus.key` as a wrapper takes care of setting `args.initiating_client`.

**Comment by blueyed** [comment]
I think https://github.com/blueyed/awesome-cyclefocus/pull/21 should fix it.
Can somebody review/confirm it, please?
