### ISSUE TITLE
Merge awesome-cyclefocus upstream?

### ISSUE THREAD

**Issue by drgibbon** [blueyed/awesome-cyclefocus#12]
I found this module from a [Stackoverflow question](https://stackoverflow.com/questions/11697102/awesome-alttab-just-switches-between-two-apps), and to my mind it fixes the very limited meta-tab / meta-j/k functionality that `awesomewm` ships with. The default functionality seems particularly strange for a tiling window manager, because meta-j/k make it quite hard to find two windows to quickly switch between with meta-tab (at least using the keyboard only, whereas it is easy with this module, as it should be).

 `awesome-cyclefocus` seems like essential functionality to me, and I think the default configuration for it is very sensible. Is there any possibility to get this included in `awesomewm` by default?

**Comment by blueyed** [comment]
Good question.
I think I should update it here first, since I am using a heavily modified version since a while myself.

**Comment by blueyed** [comment]
Updated for v4 finally by now.
The question is still valid of course.

Should get added to https://awesomewm.org/recipes/ though for now anyway.

**Comment by drgibbon** [comment]
It's working well on v4 for me. I see that it's been added to recipes which is great, although I still think this module should be shipped as default :)

**Comment by blueyed** [comment]
I see, and don't want to miss it myself, but it's really not good enough to be shipped by default I would say as of now.
Let's close this issue for now.
Thanks for your feedback!
