### ISSUE TITLE
Right Alt - Tab is not working

### ISSUE THREAD

**Issue by WscriChy** [blueyed/awesome-cyclefocus#13]
Right Alt - Tab is not working, it shows the list but the list does not disappear after the the release of the combination.

**Comment by blueyed** [comment]
Do you mean AltGr-Tab?
What config are you using?

Anyway, it reminded me that I have local enhancements since a while, which seem to be required for awesome v4 anyway: so please try https://github.com/blueyed/awesome-cyclefocus/pull/14.

**Comment by ChoppinBlockParty** [comment]
It seems still not working with (`Right Alt`): the windows get opened but it does not disappear after `Right Alt` is released. 

    cyclefocus.key({ "Mod1", }, "Tab", 1, {
        cycle_filters = { my.same_tag_name },
        keys = {'Tab', 'ISO_Left_Tab'}  -- default, could be left out
    })
