### ISSUE TITLE
Call cyclefocus with Alt+Escape

### ISSUE THREAD

**Issue by friederbluemle** [blueyed/awesome-cyclefocus#17]
I'm trying to invoke cyclefocus using `Alt+Escape`. For some reason this does not seem to work:

    awful.key({ "Mod1",           }, "Escape",
        function (c)
            cyclefocus.cycle({modifier="Alt_L"})
        end,
        {description = "cyclefocus", group = "client"}),

When I replace `Escape` with `Tab` it works as expected.
Am I missing anything?

Thanks

**Comment by friederbluemle** [comment]
I noticed this piece of code in cyclefocus:

    -- Abort on Escape.
    if key == 'Escape' then
        return exit_grabber(orig_client)
    end

After commenting it out, the wbox appears as expected. However, subsequent presses of `Escape` don't focus the next item in the list...

**Comment by blueyed** [comment]
With #29 this works:
```lua
    cyclefocus.key({altkey}, 'Escape'),
```

or
```
    cyclefocus.key({altkey}, 'Escape', {exit_key='a'}),
```

**Comment by blueyed** [comment]
I have `altkey = "Mod1"`.
Please check the debug log / output in case it does not work - I've seen it complaining about unexpected "Alt_L" in some case.  Might need to pass this in as `modifiers` then.

**Comment by blueyed** [comment]
Should be:
```
    cyclefocus.key({'Mod1'}, 'Escape', {modifer='Alt_L'}),
```
`Alt_L` gets used by default due to 0-indexing in `cyclefocus.key` currently.
Will fix it, and maybe add some mapping there.
Ref: https://github.com/blueyed/awesome-cyclefocus/issues/19
