### ISSUE TITLE
cyclefocus.key needs to have the modifier option if not using Mod1

### ISSUE THREAD

**Issue by c-meier** [blueyed/awesome-cyclefocus#19]
First at line 1071 you have :
```
    args.modifier = args.modifier or mods[0]
```
In lua the index of an array start by default at `1`,  so it should be :
```
    args.modifier = args.modifier or mods[1]
```

But that break the release as modifiers are like `Mod1` or `Mod4` or `Shift` and the key event that you listen to correspond to `Super_L` or `Alt_L`. So if you don't use `Mod1` (and get the default value of `Alt_L` as the modifier keysym) as your modifier, you need to specify the keysym of your modifier in your options.

```
cyclefocus.key({ "Mod4", }, "Tab", {
   modifier = "Super_L",
   -- cycle_filters from the default filters:
   cycle_filters = { cyclefocus.filters.same_screen, cyclefocus.filters.common_tag }
 })
```

**Comment by blueyed** [comment]
Thanks for the report - https://github.com/blueyed/awesome-cyclefocus/pull/30 should fix/handle this.
