### ISSUE TITLE
Some selected icons are using lower resolution versions even when high is available

### ISSUE THREAD

**Issue by ryukinix** [blueyed/awesome-cyclefocus#20]
Example:
![low-resolution-icons](https://user-images.githubusercontent.com/7642878/32357748-46c608aa-c01e-11e7-8d83-d535a8d509e2.png)

(firefox nightly is low resolution)

There any specific reason on it? The same happens with other softwares too, like `Gimp`, `Zeal` and much others.

**Comment by ryukinix** [comment]
Lack of activity

**Comment by blueyed** [comment]
Might want to use https://github.com/awesomeWM/awesome/blob/master/lib/awful/widget/clienticon.lua.

**Comment by blueyed** [comment]
#33
